### ISSUE TITLE
I found 2 bugs.

### ISSUE THREAD

**Issue by JaroSound** [TanguyOrtegat/esx_jb_advanced_truck_inventory#1]
1 - The trunk does not open.
2 - When I have the trunk menu open, I can not get out of it by pressing the backspace.

**Comment by TanguyOrtegat** [comment]
you tried to change keys to open the trunk ? 
trunk should close, no one is complaining about :)

**Comment by Tanoshi-Shinto** [comment]
the trunk opens fine but pressing backspace to exit is slow and some times you have to press a few times.

**Comment by TanguyOrtegat** [comment]
should normally be repaired by @SaltyGrandpa

**Comment by csnabanipl** [comment]
Three trunk od stil not opening... Menu works fine.
