### ISSUE TITLE
Deletes Items

### ISSUE THREAD

**Issue by BryBTG** [TanguyOrtegat/esx_jb_advanced_truck_inventory#18]
Deletes all items on database when server restarts

**Comment by TanguyOrtegat** [comment]
becasue the car is not owned by you

**Comment by TanguyOrtegat** [comment]
look at the fix today or :
@esx_jb_advanced_truck_inventory\server\main.lua

line 29:
AddEventHandler('onMySQLReady', function ()
MySQL.Async.execute( 'DELETE FROM truck_inventory WHERE owned = 0 OR count = 0', {})

put this :
--[[
AddEventHandler('onMySQLReady', function ()
MySQL.Async.execute( 'DELETE FROM truck_inventory WHERE owned = 0 OR count = 0', {})
end)--]]
