### ISSUE TITLE
When i start the server the info on the table is deleted

### ISSUE THREAD

**Issue by ChapiChapi** [TanguyOrtegat/esx_jb_advanced_truck_inventory#19]
And the car is owned by me

**Comment by TanguyOrtegat** [comment]
check server event onmysql ready or something like that

**Comment by StarZNighT** [comment]
@esx_jb_advanced_truck_inventory\server\main.lua

line 29: 
AddEventHandler('onMySQLReady', function ()
	MySQL.Async.execute( 'DELETE FROM `truck_inventory` WHERE `owned` = 0 OR `count` = 0', {})

put this :
 --[[
AddEventHandler('onMySQLReady', function ()
	MySQL.Async.execute( 'DELETE FROM `truck_inventory` WHERE `owned` = 0 OR `count` = 0', {})
end)--]]

**Comment by TanguyOrtegat** [comment]
or look at my fix today
