### ISSUE TITLE
Glitch/Duplication

### ISSUE THREAD

**Issue by nykroza** [TanguyOrtegat/esx_jb_advanced_truck_inventory#6]
The code that check if a player is already in the trunk doesn't always work.
If the owner of the car check the trunk, nobody else can check it..
but if a player check the trunk, then the owner can check it also..

If both player select the same item when withrawing and both press Okay at the same time, both person will receive the amount of the item. So if they have 50 000 black money and do that, they will both receive 50 000, replace it in the trunk, redo it and now they both have 100 000 black money

**Comment by RedAlex** [comment]
Fix here https://github.com/TanguyOrtegat/esx_jb_advanced_truck_inventory/pull/10
