### ISSUE TITLE
Can't add items into the trunk

### ISSUE THREAD

**Issue by MoravianLion** [TanguyOrtegat/esx_jb_advanced_truck_inventory#7]
[ERROR] [MySQL] An error happens on MySQL for query "INSERT INTO truck_inventory  (item,count,plate,name,itemt,owned) VALUES (@item,@qty,@plate,@name,@itemt,@owned) ON DUPLICATE KEY UPDATE count=count+ @qty {@itemt=item_weapon;@owned=1;@plate=21HJV221;@name=Micro smg;@item=WEAPON_MICROSMG;@qty=250}": Unknown column 'itemt' in 'field list'

Any idea what's wrong?

**Comment by TanguyOrtegat** [comment]
you don't have itemt in your database, juste read the error ...
